//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperCareServicesGroup
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssignedEmployee
    {
        public int AssignedEmployeeID { get; set; }
        public int QuoteRequestID { get; set; }
        public int RegisteredEmployeeID { get; set; }
        public System.DateTime AssignedAt { get; set; }
    
        public virtual QuoteRequest QuoteRequest { get; set; }
        public virtual RegisteredEmployee RegisteredEmployee { get; set; }
    }
}
