//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperCareServicesGroup
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssignedQuote
    {
        public int AssignmentID { get; set; }
        public int QuoteRequestID { get; set; }
        public int RegisteredEmployeeId { get; set; }
        public System.DateTime AssignmentDate { get; set; }
        public string Status { get; set; }
        public string Notes { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public Nullable<System.DateTime> ScheduledDate { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
        public Nullable<int> CustomerRating { get; set; }
        public string CustomerFeedback { get; set; }
    
        public virtual QuoteRequest QuoteRequest { get; set; }
        public virtual RegisteredEmployee RegisteredEmployee { get; set; }
    }
}
