//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperCareServicesGroup
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookCleaning
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BookCleaning()
        {
            this.BookCleaningEmployees = new HashSet<BookCleaningEmployee>();
            this.CustomerFeedbacks = new HashSet<CustomerFeedback>();
        }
    
        public int BookCleaningID { get; set; }
        public int QuoteRequestID { get; set; }
        public string CustomerName { get; set; }
        public string CleaningType { get; set; }
        public string Details { get; set; }
        public string CustomerLocation { get; set; }
        public Nullable<System.DateTime> PreferredDate { get; set; }
        public Nullable<int> DaysRemaining { get; set; }
        public Nullable<decimal> CleaningAmount { get; set; }
        public Nullable<decimal> Deposit { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public bool DepositPaid { get; set; }
        public string TimeSlot { get; set; }
        public bool Assigned { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string ServiceLevel { get; set; }
        public bool JobStarted { get; set; }
        public Nullable<System.TimeSpan> CompletionTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookCleaningEmployee> BookCleaningEmployees { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual QuoteRequest QuoteRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerFeedback> CustomerFeedbacks { get; set; }
    }
}
