//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperCareServicesGroup
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerFeedback
    {
        public int CustomerId { get; set; }
        public int BookCleaningID { get; set; }
        public string CleaningType { get; set; }
        public string CustomerName { get; set; }
        public string Feedback { get; set; }
        public Nullable<int> Rating { get; set; }
        public string ServiceLevel { get; set; }
    
        public virtual BookCleaning BookCleaning { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
