//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperCareServicesGroup
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuoteRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QuoteRequest()
        {
            this.BookCleanings = new HashSet<BookCleaning>();
        }
    
        public int QuoteRequestID { get; set; }
        public int CustomerID { get; set; }
        public string CleaningType { get; set; }
        public string Details { get; set; }
        public System.DateTime PreferredDate { get; set; }
        public string CustomerLocation { get; set; }
        public string Status { get; set; }
        public System.DateTime SubmittedAt { get; set; }
        public Nullable<decimal> QuoteAmount { get; set; }
        public Nullable<int> AssignedEmployeeID { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
        public bool IsPaid { get; set; }
        public string ServiceLevel { get; set; }
        public bool Confirmation { get; set; }
        public string CustomerName { get; set; }
        public string Feedback { get; set; }
        public Nullable<decimal> CleaningAmount { get; set; }
        public bool AllowBooking { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual RegisteredEmployee RegisteredEmployee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookCleaning> BookCleanings { get; set; }
    }
}
