//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperCareServicesGroup
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegisteredEmployee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RegisteredEmployee()
        {
            this.EmployeeClockings = new HashSet<EmployeeClocking>();
            this.QuoteRequests = new HashSet<QuoteRequest>();
            this.BookCleaningEmployees = new HashSet<BookCleaningEmployee>();
        }
    
        public int RegisteredEmployeeID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public string PasswordHash { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public bool IsActive { get; set; }
        public string ProfilePic { get; set; }
        public string SkillQualification { get; set; }
        public string BarcodePath { get; set; }
        public string AlphaNumericVal { get; set; }
        public bool HasBeenAssigned { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeClocking> EmployeeClockings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuoteRequest> QuoteRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookCleaningEmployee> BookCleaningEmployees { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
