//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperCareServicesGroup
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServicePackage
    {
        public int Id { get; set; }
        public string Standard { get; set; }
        public string Deep { get; set; }
        public string Disinfection { get; set; }
        public string PostEvent { get; set; }
        public string Move { get; set; }
    }
}
