//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperCareServicesGroup
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SuperCareServicesNewEntities1 : DbContext
    {
        public SuperCareServicesNewEntities1()
            : base("name=SuperCareServicesNewEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<EmployeeClocking> EmployeeClockings { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Manager> Managers { get; set; }
        public virtual DbSet<QuoteRequest> QuoteRequests { get; set; }
        public virtual DbSet<RegisteredEmployee> RegisteredEmployees { get; set; }
        public virtual DbSet<BookCleaningEmployee> BookCleaningEmployees { get; set; }
        public virtual DbSet<BookCleaning> BookCleanings { get; set; }
        public virtual DbSet<CustomerFeedback> CustomerFeedbacks { get; set; }
        public virtual DbSet<ServicePackage> ServicePackages { get; set; }
    }
}
